### ISSUE TITLE
Hardware + software block diagrams

### ISSUE THREAD

**Issue by npes-95** [Ranuncolo/umbrella#1]
Useful for quickly understanding how your system works.

- Team 4

**Comment by danmarwick** [comment]
Hi! I've added a block diagram on our front page showing a flow of information through this system. Is this what you had in mind?

Daniel - Team 13

**Comment by danmarwick** [comment]
I'll assume the block diagram is clear enough and close this issue.  If you have any other comments then let us know and we'll be happy to make updates!

Daniel - Team 13
