### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by alex-angelov** [Ranuncolo/umbrella#2]
1) There is no list of exact component models/manufacturers, or a sketch/CAD of the system design;
2) Power considerations - will the Pi (assuming you won't use a PSU) be able to supply enough power for the motor;
3) If it is operating outside, what kind of weather protection (electronics) are you going to implement? How are you powering the system?
4) A small schematic outlining a typical example with a garden and sensor locations would be great for visualization;
5) Maybe write the name of the sensors, because components can disappear from stores with time.
Good idea overall.
-Team 11

**Comment by danmarwick** [comment]
Hi Alex!  

This would be much easier to deal with as 5 separate issues! :-)  I'll answer what I can just now and we'll get back to you when we can answer the other issues.

1. Sensor model names have been added.  Details of the system design will follow shortly.

2. There is no motor involved in this project - you may be thinking of one of the many other weather stations!  Our components are all just sensors that can be easily powered through the 3.3V pin.

3. We're looking to place this outside with battery power and a 3D printed case to keep the system dry.

4. Our system will be a small self contained box with some sensors so I'm not sure this is applicable.

5.  Excellent idea!  Done!

If any other issues come to mind then please let us know! Any feedback is useful.

Daniel - Team 13

**Comment by danmarwick** [comment]
Hi Alex,
We've now included the design of our PCB and added our hardware details.  Is there anything else you would like cleared up?

Daniel - Team 13

**Comment by alex-angelov** [comment]
I think this is all, great work!
