### ISSUE TITLE
Maybe add a photo of the whole system flow is better to understand

### ISSUE THREAD

**Issue by JiananKan** [Ranuncolo/umbrella#3]
team6

**Comment by danmarwick** [comment]
Hi Jianan!  

I've added a block diagram on our front page showing a flow of information through this system.  Is this what you had in mind?

Daniel - Team 13

**Comment by danmarwick** [comment]
Hi Jianan,

I'll assume the block diagram is clear enough and close this issue. If you have any other comments then let us know and we'll be happy to make updates!

Daniel - Team 13
