### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by tamercos** [Ranuncolo/umbrella#4]
Unless I missed it, installation instructions would be helpful!

-team 16

**Comment by danmarwick** [comment]
Hi Tamer,
Excellent idea!  Web app installation instructions are live.  Installation instructions for the other aspects will follow shortly.

Daniel - Team 13

**Comment by danmarwick** [comment]
Hi Tamer,
We've now included installation and setup instructions for the rest of our software.  Is there anything else you would like us to add or expand on?

Daniel - Team 13
