### ISSUE TITLE
Could we see what you're doing to get this project to completion?

### ISSUE THREAD

**Issue by acra6488** [Ranuncolo/umbrella#5]
Do you have any pictures of testing, or a link to a social media page?
Which parts have caused problems and how did you solve them? Perhaps this could appear in your Wiki under a "Troubleshooting" section.
-Aurelie -Team 2

**Comment by danmarwick** [comment]
Hi Aurelie,

1. We've been testing the project continuously in the lab over the last few weeks but unfortunately we haven't documented our initial testing with pictures or video.  We didn't think our initial poorly wired bread board could be used for any effective marketing!

2. Social media links are included at the bottom of our main page.  Our social media campaign should start up soon as the final design comes together.

3. Great idea with the troubleshooting section!  I've combined this with Tamer's idea for the installation guide so prospective users can get up and running while avoiding all the pit falls we did!

Daniel - Team 13

**Comment by danmarwick** [comment]
Hi Aurelie,
Following up with this - we've now added some notes on problem solving and troubleshooting to our installation guide for all parts of the project.  We've also started our social media campaign! 

Twitter: https://twitter.com/UmbrellaRPI 
Facebook: https://www.facebook.com/UmbrellaRPI/

Is there anything else you would like us to add or expand on?

Daniel - Team 13
