### ISSUE TITLE
Repo Structuring

### ISSUE THREAD

**Issue by CalumWest** [Ranuncolo/umbrella#6]
More explicit structuring of repository including hardware specs/resources and code structuring would be useful

**Comment by danmarwick** [comment]
Hi Calum,

1. We've cleared up our repository so the code structure should be clearer.  Web app code, SPI code for wind sensors and I2C code for everything else is currently separated.  We're currently working on bringing it all together.

2. Hardware specifications are on the front page and our PCB design have now been included.

Is that all good? Is there anything else you would like cleared up?

Daniel - Team 13
